id: P010630
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG25264
  title: འདུལ་བའི་སྡེ་སྣོད་ལེགས་བཤད་སྐལ་བཟང་ནོར་བུའི་ཕྲེང་བ།
  author: ''
  volumes:
    9025f5d27afd4210be102b3076ccec80:
      image_group_id: I1KG25266
      title: ''
      volume_number: 1
      total_pages: 448
      base_file: v001.txt
