id: P010630
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 2021-12-20 10:17:17.120514
source_metadata:
  id: bdr:W1KG25264
  title: འདུལ་བའི་སྡེ་སྣོད་ལེགས་བཤད་སྐལ་བཟང་ནོར་བུའི་ཕྲེང་བ།
  author: ''
  volumes:
    9025f5d27afd4210be102b3076ccec80:
      image_group_id: I1KG25266
      title: ''
      volume_number: 1
      total_pages: 448
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
