id: I4B07A4C6
legacy_id: P010630
ocr_import_info:
  bdrc_scan_id: W1KG25264
  source: bdrc
  ocr_info:
    timestamp: '2020-03-29T15:56:15'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-27T08:03:25.975292+00:00'
last_modified: 2022-08-27 16:04:03.089017
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG25264
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1KG25264
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: འདུལ་བའི་སྡེ་སྣོད་ལེགས་བཤད་སྐལ་བཟང་ནོར་བུའི་ཕྲེང་བ།
  author: པཎ་ཆེན་བདེ་ལེགས་ཉི་མ།
statistics:
  ocr_word_mean_confidence_index: 0.9495733360210782
  ocr_word_median_confidence_index: 0.9900000095367432
quality: null
bases:
  I1KG25266:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG25266
      total_pages: 448
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG25266.txt
    statistics:
      ocr_word_median_confidence_index: 0.9900000095367432
      ocr_word_mean_confidence_index: 0.9495733360210782
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
